[2022-09-24T19:06:26.915+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.dbt_test manual__2022-09-24T19:06:25.452518+00:00 [queued]>
[2022-09-24T19:06:26.936+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.dbt_test manual__2022-09-24T19:06:25.452518+00:00 [queued]>
[2022-09-24T19:06:26.937+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-24T19:06:26.937+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-24T19:06:26.937+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-24T19:06:26.967+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): dbt_test> on 2022-09-24 19:06:25.452518+00:00
[2022-09-24T19:06:26.976+0000] {standard_task_runner.py:54} INFO - Started process 103 to run task
[2022-09-24T19:06:26.981+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_test', 'manual__2022-09-24T19:06:25.452518+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpbfs9m8mp']
[2022-09-24T19:06:26.982+0000] {standard_task_runner.py:83} INFO - Job 111: Subtask dbt_test
[2022-09-24T19:06:26.983+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-24T19:06:27.112+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.dbt_test manual__2022-09-24T19:06:25.452518+00:00 [running]> on host 1e3e39d515da
[2022-09-24T19:06:27.264+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_test
AIRFLOW_CTX_EXECUTION_DATE=2022-09-24T19:06:25.452518+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-24T19:06:25.452518+00:00
[2022-09-24T19:06:27.265+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-24T19:06:27.266+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt test']
[2022-09-24T19:06:27.281+0000] {subprocess.py:86} INFO - Output:
[2022-09-24T19:06:27.284+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2022-09-24T19:06:27.285+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-24T19:06:27.306+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-24T19:06:27.314+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_test, execution_date=20220924T190625, start_date=20220924T190626, end_date=20220924T190627
[2022-09-24T19:06:27.338+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 111 for task dbt_test (Bash command failed. The command returned a non-zero exit code 127.; 103)
[2022-09-24T19:06:27.353+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-24T19:06:27.384+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
