[2022-09-23T22:02:58.738+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.dbt_run scheduled__2022-09-22T00:00:00+00:00 [queued]>
[2022-09-23T22:02:58.748+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.dbt_run scheduled__2022-09-22T00:00:00+00:00 [queued]>
[2022-09-23T22:02:58.749+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-23T22:02:58.749+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-23T22:02:58.749+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-23T22:02:58.760+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): dbt_run> on 2022-09-22 00:00:00+00:00
[2022-09-23T22:02:58.766+0000] {standard_task_runner.py:54} INFO - Started process 104 to run task
[2022-09-23T22:02:58.769+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_run', 'scheduled__2022-09-22T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt.py', '--cfg-path', '/tmp/tmpwyf75syh']
[2022-09-23T22:02:58.769+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask dbt_run
[2022-09-23T22:02:58.770+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt.py
[2022-09-23T22:02:58.824+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.dbt_run scheduled__2022-09-22T00:00:00+00:00 [running]> on host 1950b3c63e7c
[2022-09-23T22:02:58.887+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2022-09-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-22T00:00:00+00:00
[2022-09-23T22:02:58.903+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-23T22:02:58.904+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run']
[2022-09-23T22:02:58.917+0000] {subprocess.py:86} INFO - Output:
[2022-09-23T22:02:58.949+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2022-09-23T22:02:58.949+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-23T22:02:58.961+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-23T22:02:58.966+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dbt_dag, task_id=dbt_run, execution_date=20220922T000000, start_date=20220923T220258, end_date=20220923T220258
[2022-09-23T22:02:58.978+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 104)
[2022-09-23T22:02:59.021+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-23T22:02:59.066+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
